### ISSUE TITLE
No longer works in ElkArte 1.1.x

### ISSUE THREAD

**Issue by kode54** [Spuds/Elk_Inline_Attachments#2]
Basically, non functional as of 1.1.x, even with it using 1.0 emulation for the extension.

**Comment by Spuds** [comment]
1.1 has ILA built in ... So you should not need this addon.

**Comment by kode54** [comment]
How do I enable the tags to allow manually inlining links or embedded images, like this addon allowed?

**Comment by Spuds** [comment]
There is a setting in the ACP->Attachments .... "Enable the display of in line attachments"  its at the bottom area of that page.

Its been a while, but I recall the tags are close to what this addon had, but not 100% compatible, mainly due to being part of the core allowed more flexibility in how it was implemented.  I think there was a simple translation query posted on the site to change them over.
